# base configuration

version: '2.1'
services:
  base-eureka:
    command: []



    environment:
    - CONTAINER_HOST_NAME=${CONTAINER_HOST_NAME:-eureka-peer1}
    - EUREKA_CLIENT_FETCHREGISTRY=${EUREKA_CLIENT_FETCHREGISTRY:-true}
    - EUREKA_CLIENT_REGISTERWITHEUREKA=${EUREKA_CLIENT_REGISTERWITHEUREKA:-true}
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@eureka-peer1:8761/eureka/}
    - EUREKA_INSTANCE_HOSTNAME=${CONTAINER_HOST_NAME:-eureka-peer1}
    - EUREKA_INSTANCE_IPADDRESS=${HOST_IPADDRESS:-127.0.0.1}
    - EUREKA_INSTANCE_NONSECUREPORT=${SERVER_PORT:-8761}
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-false}
    - EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT=${EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT:-0}
    - EUREKA_SERVER_ENABLESELFPRESERVATION=${EUREKA_SERVER_ENABLESELFPRESERVATION:-true}
    - EUREKA_SERVER_RENEWALPERCENTTHRESHOLD=${EUREKA_SERVER_RENEWALPERCENTTHRESHOLD:-0.85}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SERVER_PORT=${SERVER_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-eureka-cluster}
    #- SPRING_CLOUD_CLIENT_HOSTNAME=${HOST_IPADDRESS} # profile: manual_ip_hostname
    #- SPRING_CLOUD_CLIENT_IPADDRESS=${HOST_IPADDRESS} # profile: manual_ip_hostname
    - SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS=${SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS}
    - SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES=${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES}
    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-develop.env,port_nonsecure,peer_awareness}
    - SPRING_SECURITY_ENABLED=${SPRING_SECURITY_ENABLED:-true}
    - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME:-user}
    - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD:-user_pass}
    image: ${IMAGE_PREFIX:-cloudready/}spring-cloud-eureka-server:${IMAGE_TAG:-1.0.1.U1}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.eureka}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/eureka/standalone}
    restart: always
