eureka:
  client:
    enabled: true
    register-with-eureka: true
    #registry-fetch-interval-seconds: ${EUREKA_CLIENT_REGISTRYFETCHINTERVALSECONDS:5}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://user:user_pass@standalone.eureka:8761/eureka/}
  instance:
    health-check-url: ${sidecar.health-uri}
    #health-check-url-path: ${server.servlet.context-path}${management.endpoints.web.base-path}/health
    # eureka.instance.hostname affect Status->instances's url href (not text) value on dashboard
    hostname: ${SPRING_CLOUD_CONSUL_DISCOVERY_HOSTNAME:${EUREKA_INSTANCE_HOSTNAME:${SPRING_CLOUD_CLIENT_HOSTNAME:${eureka.instance.ip-address:localhost}}}}
    ip-address: ${SPRING_CLOUD_CONSUL_DISCOVERY_IPADDRESS:${EUREKA_INSTANCE_IPADDRESS:${HOST_IPADDRESS:${spring.cloud.client.ip-address}}}}
    home-page-url: ${sidecar.home-page-uri}
    instance-id: ${spring.application.name}:${sidecar.hostname}:${SERVER_PORT:5678}
    metadataMap:
      applicationId: ${spring.application.name}

      management.context-path: ${server.servlet.context-path}${management.endpoints.web.base-path}
      management.port: ${management.server.port}
      health.path: "health"
      startup: ${random.int}
      user.name: ${spring.security.user.name:}
      user.password: ${spring.security.user.password:}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFERIPADDRESS:false}
    status-page-url: http://${sidecar.hostname}:${sidecar.port}${eureka.instance.status-page-url-path}
    status-page-url-path: ${server.servlet.context-path}${management.endpoints.web.base-path}${SIDECAR_STATUSPAGEURI:/info}

# logging request & response info, style can be http, curl, json, splunk
logbook:
  #exclude:
  include: "/**"
  format:
    style: ${LOGBOOK_FORMAT_STYLE:http}
  obfuscate:
    headers:
      #- Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  write:
    max-body-size: 2000

logging:
  config: classpath:logback-spring.xml
  file: ${LOGGING_FILE:logs/spring.log}
  #file: ${LOGGING_FILE:${LOG_FILE:${eureka.instance.hostname}-${server.port}.log}}
  #path: ${LOGGING_PATH:${LOG_PATH:${user.dir}/data/logs/${spring.application.name}}}
  level:
    jndi: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.boot.actuate.endpoint.jmx.EndpointMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.actuate.endpoint.mvc.EndpointHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.web.servlet.FilterRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.boot.web.servlet.ServletRegistrationBean: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.core.type.classreading.AnnotationAttributesReadingVisitor: INFO
    org.springframework.jmx.export.annotation.AnnotationMBeanExporter: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.jndi: ${LOGGING_LEVEL_ROOT:INFO}
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: ${ENDPOINT_LOGGING_LEVEL_ROOT:WARN}
    root: ${LOGGING_LEVEL_ROOT:DEBUG}

management:
  endpoint:
    shutdown.enabled: ${MANAGEMENT_ENDPOINT_SHUTDOWN_ENABLED:true}
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS:ALWAYS}
      roles: ${MANAGEMENT_ENDPOINT_HEALTH_ROLES:ACTUATOR}
  endpoints:
    jmx:
      exposure:
        exclude: "${MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_EXCLUDE:}"
        include: "${MANAGEMENT_ENDPOINTS_JMX_EXPOSURE_INCLUDE:*}"
    web: # since spring-boot 2.x
      base-path: ${MANAGEMENT_ENDPOINTS_WEB_BASEPATH:/actuator} # do not change this value on sidecar (management.context-path deprecated since spring-boot 2.x)
      exposure:
        include: "${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:*}"
        exclude: "${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_EXCLUDE:}"
#  security: # deprecated since spring-boot 2.x
#    enabled: true
#    roles: SUPERUSER
#    sessions: stateless
  server:
    port: ${server.port}

#endpoints: # deprecated since spring-boot 2.x
#  env.sensitive: ${ENDPOINTS_ENV_SENSITIVE:true}
#  health.sensitive: ${ENDPOINTS_HEALTH_SENSITIVE:false}

server:
  port: ${SERVER_PORT:5678}
  servlet.context-path: ${SERVER_SERVLET_CONTEXTPATH:} # do not change server.servlet.context-path on sidecar, since spring-boot 2.x (server.context-path deprecated since spring-boot 2.x)
  #context-path: ${SERVER_CONTEXTPATH:} # deprecated since spring-boot 2.x

sidecar:
  health-uri: ${SIDECAR_HEALTHURI:http://standalone.eureka:8761/actuator/health} # mandatory
  home-page-uri: ${SIDECAR_HOMEPAGEURI:http://standalone.eureka:8761} # optional
  hostname: ${SIDECAR_HOSTNAME:${sidecar.ip-address:standalone.eureka}} # optional
  ip-address: ${SIDECAR_IPADDRESS:} # optional
  # sidecar.port is the port on which the non-JVM application listens
  port: ${SIDECAR_PORT:8761} # mandatory

spring:
  application.name: ${SPRING_APPLICATION_NAME:the-name-of-non-JVM-application-or-service}
  cloud:
    inetutils:
      preferred-networks: ${SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS:^192\.168\..+, ^172\.30\..+, ^10\..+}
      ignored-interfaces: ${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES:^[a-z]?tun[0-9]*, ^awdl[0-9]*, ^lo[0-9]*}

  security:
    enabled: false
    user:
      name: ${SPRING_SECURITY_USER_PASSWORD:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user_pass}
      roles: ${SPRING_SECURITY_USER_ROLES:ACTUATOR, ADMIN, SUPERUSER, USER}
