version: '2.1'
services:
  consul-client:
    extends:
      file: docker-compose-base.yml
      service: base-consul-agent
    # -dns-port=53 needs 'network_mode: host'
    command: ${COMMAND:-agent -bind=0.0.0.0 -client=0.0.0.0 -dns-port=53 -retry-join=127.0.0.1 -retry-interval=30s -retry-max=0 -ui=true} # change me
    container_name: ${CONTAINER_HOST_NAME:-consul-client}
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 1
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE:-eth0}
    hostname: ${CONTAINER_HOST_NAME:-consul-client}
    network_mode: ${NETWORK_MODE:-host}
    #ports: # for network_mode: bridge
    #- "${CONSUL_DNS_PORT:-53}:53/tcp"
    #- "${CONSUL_DNS_PORT:-53}:53/udp"
    #privileged: true
    volumes:
    - data:/consul/data
    - /etc/resolv.conf:/var/lib/host_etc_resolv.conf

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
