# production development configuration

version: '2.1'
services:
  eureka-sidecar:
    extends:
      file: docker-compose-base.yml
      service: base-eureka-sidecar
    container_name: ${CONTAINER_HOST_NAME:-eureka-sidecar}
    environment:
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-false}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SERVER_PORT=${SERVER_PORT:-5678}
    - SIDECAR_HEALTHURI=${SIDECAR_HEALTHURI:-http://standalone.eureka:8761/actuator/health}
    - SIDECAR_HOMEPAGEURI=${SIDECAR_HOMEPAGEURI:-http://standalone.eureka:8761}
    - SIDECAR_HOSTNAME=${SIDECAR_HOSTNAME:-standalone.eureka}
    - SIDECAR_IPADDRESS=${SIDECAR_IPADDRESS} # Optional
    - SIDECAR_PORT=${SIDECAR_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-the-name-of-non-JVM-application-or-service}
    - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME:-user}
    - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD:-user_pass}
    hostname: ${CONTAINER_HOST_NAME:-eureka-sidecar}
    network_mode: bridge
    ports:
    - "${SERVER_PORT:-5678}:${SERVER_PORT:-5678}"
    volumes:
    - data:/home/alpine/data
    - tmp:/tmp

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  tmp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/tmp
      o: bind
